### ISSUE TITLE
Project name not available for docking time.

### ISSUE THREAD

**Issue by motwanideepika-ee** [EqualExperts/minutedock#10]
My project has been added but I can't see my project in the list.
Project name is : @elsevier #onshore

**Comment by douglas-vaz** [comment]
Hi Deepika, projects are pulled from the minutedock server and not configured in this app. Please check with TJ/Shashi about this.

**Comment by motwanideepika-ee** [comment]
Hi Douglas,

My project is visible in minutedock but not in time.equalexperts
I tried refreshing the projects but the project is still not visible.

Regards,
Deepika

**Comment by devaroop** [comment]
There are two entities in Minute Dock namely:

1. Contacts - Project Headers like O2, HMRC, etc
2. Projects - Specifics of each contact viz O2_Priority, O2_Ecom, etc

While creating `Projects` please prefix them with the Project Name. For e.g. -

Project named `O2 Offshore` was being created as `@O2` (contact) and `#offshore` (project). Instead create it as `@O2` (contact) and `#o2_offshore` (project, notice the prefix) to show up correctly in the projects' list on the app.

If you still see the project, use the `Refresh Projects` link, take a deep breath and check again. 

If you still fail to retrieve, please check for the project on minute dock and re-open this ticket with specifics. Thanks.
