### ISSUE TITLE
Load environment specific config parameters from Environment Variables

### ISSUE THREAD

**Issue by douglas-vaz** [EqualExperts/minutedock#6]
At the moment, config parameters such as Google OAuth tokens are pulled from source files in config which forces the user to modify code before running the app. Also, there's a potential risk for sensitive config params being checked into the source code repo. Reading the values from the environment would be a better strategy IMO

**Comment by douglas-vaz** [comment]
node_config provides two ways of reading from environment vars:

1) Provide a JSON string to the environment variable NODE_CONFIG which overrides the values provided in the config files. https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config

2) Create a custom JSON file which flattens the environment variables https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

The first approach seems cleaner IMO. Comments?

**Comment by anshulbajpai** [comment]
I'll recommend to externalise the config file using environment variable.
Version the production config file in a different private repository.

**Comment by douglas-vaz** [comment]
Well we're thinking of having a config file that reads values from environment variables (process.env.*). We can then specify values in something like a foreman .env file (which gulp can inject into the environment before starting the server) or set via the CI. This allows us to have defaults checked into the repository and is transparent to what is configurable.

**Comment by anshulbajpai** [comment]
How will you do it in production? Are you going to ship your build file
with the distribution?
